---
name: Links

on:
  push:
    branches:
      - main
      - renovate/**
  pull_request:

jobs:
  links:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      # yamllint disable-line rule:line-length
      - uses: paddyroddy/.github/actions/links@4694929eae9f35951321f455a46bd7d7d32ccf5f # v0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
