---
name: Links

on:
  push:
    branches:
      - main
      - renovate/**
  pull_request:

jobs:
  links:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      # yamllint disable-line rule:line-length
      - uses: paddyroddy/.github/actions/links@d5aea086eaabccae4bcf39786ad5138b629755a6 # v0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
