---
name: Linting

on:
  push:
    branches:
      - main
      - renovate/**
  pull_request:

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      # yamllint disable-line rule:line-length
      - uses: paddyroddy/.github/actions/linting@4694929eae9f35951321f455a46bd7d7d32ccf5f # v0
        with:
          pre-commit-config: ./.pre-commit-config.yaml
