---
name: Quarto Publish

on:
  push:
    branches:
      - main
      - renovate/**
  pull_request:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # yamllint disable-line rule:line-length
      - uses: paddyroddy/.github/actions/github-pages/quarto@b9cde8bcbbce838802ecd0aba2c3a7f8b82f519c # v0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
